### ISSUE TITLE
Pandoc 3x support

### ISSUE THREAD

**Issue by JessicaTegner** [JessicaTegner/pypandoc#321]
This issue is to track support for pandoc 3x

There's a bunch of things added and removed, but most notable is a change in lua filters and filters in general.
More information can be found on [Pandoc Release Page](https://pandoc.org/releases.html)

**Comment by JessicaTegner** [comment]
With the release of Pandoc 3x, some test cases are breaking

Notably:

```
# test case to get installed pandoc version, should be easy to fix
FAIL: test_get_pandoc_version (__main__.TestPypandoc.test_get_pandoc_version)                                           
----------------------------------------------------------------------                                                  
Traceback (most recent call last):                                                                                      
  File "C:\Users\jessi\Desktop\GitHub\pypandoc\tests.py", line 161, in test_get_pandoc_version                          
    self.assertTrue(major in [0, 1, 2])                                                                                 
AssertionError: False is not true                                                                                       

``` 


```
# and this one, which has something to do with lua.
ERROR: test_convert_with_custom_writer (__main__.TestPypandoc.test_convert_with_custom_writer)                          
----------------------------------------------------------------------                                                  
Traceback (most recent call last):                                                                                      
  File "C:\Users\jessi\Desktop\GitHub\pypandoc\tests.py", line 255, in test_convert_with_custom_writer                  
    received = pypandoc.convert_file(file_name, lua_file_name)                                                          
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                          
  File "C:\Users\jessi\Desktop\GitHub\pypandoc\pypandoc\__init__.py", line 170, in convert_file                         
    return _convert_input(discovered_source_files, format, 'path', to, extra_args=extra_args,                           
           ^File "C:\Users\jessi\Desktop\GitHub\pypandoc\pypandoc\__init__.py", line 420, in _convert_input                       
    raise RuntimeError(                                                                                                 
RuntimeError: Pandoc died with exitcode "4" during conversion: C:\Users\jessi\AppData\Local\Temp\tmpfklv5iujfoo-bar+baz\tmpklk6nzjg.lua does not contain a custom writer                                                                        
 
```

As said, the first one is really simple to fix, but we'll need to investigate why the second one broke

This could possibly also fix #317
